alphagov/performanceplatform-collector

pep-it.sh
requirements_for_tests.txt

Bump pep8 and 'fix' version.
Ignore E402 when running tests - see https://github.com/jcrocholl/pep8/issues/264

Bump pep8 and ignore E402 error

---

pep-it.sh
performanceplatform/collector/crontab.py
tests/performanceplatform/collector/test_crontab.py

This should ensure there is a unique list of cronjobs on both machines.
backend-app-1 should only run oddly numbered jobs, backend-app-2 evenly
numbered jobs.
This change also requires a change in pp-deployment to deploy the
collectors to both machines.

Run cronjobs on multiple machines

---

tests/performanceplatform/collector/test_crontab.py

This test is failing because it runs in a separate python process, which
is not affected by the patched mock.
This test is testing that a cronjob passed in through stdin is appearing
in the output, which due to previous changes is now dependant on the
machines hostname.
This is is tested in other tests which call generate_crontab directly,
so it is not necessary to duplicate it here

Remove failing tests

---

performanceplatform/collector/webtrends/reports.py
tests/fixtures/webtrends_v3.json
tests/performanceplatform/collector/webtrends/test_reports.py

This should allow us to support NHS choices.
To use V3 of the webtrends api, ensure you are using a v3 url and ensure that you add 'api_version': 'v3' to the credentials dict in pp-deployment.
This is tested and working against the browser data report.

Tests and code for for version three

---

performanceplatform/utils/http_with_backoff.py

The current exponential back-off is a coarse-grained approach to handle
the error. It was introduced in
https://www.pivotaltracker.com/story/show/70748592 and we have:
- 503 Server Unavailable is sensible to use exponential back-off
and retry
- 502 Bad Gateway could be due to a backend system timing out
(due to load) so again, we think it reasonable to retry
– 403 Forbidden is a weird one. Google Analytics returns a 403
status code but it can mean a bunch of things. See
https://developers.google.com/analytics/devguides/reporting/core/v3/coreErrors
So (for GA at least) we need to check one or more of:
* the reason
* the response body, test that it's JSON and parse it
We probably want to make this back-off strategy pluggable, so that we can
handle how:
* Google says not to retry on 503s, …

Add more information around HTTP issues

---

tests/performanceplatform/collector/test_crontab.py

Not immediately obvious when reading that 3 candidate jobs leads to 3
line output, which includes a comment header, a single job and a comment
footer.
Added code to make that explicit.

Clarify crontab generation behaviour

---

performanceplatform/utils/http_with_backoff.py
tests/performanceplatform/utils/test_http_with_backoff.py

https://developers.google.com/analytics/devguides/reporting/core/v3/coreErrors 
shows the error content that Google can return. We should use this to
provide more intelligent error handling.

Use Google error responses

---

performanceplatform/collector/ga/contrib/content/table.py
tests/performanceplatform/collector/ga/contrib/content/test_table.py

Google Analytics Universal  does not support for custom variables so we need to change the variable we are filtering on to search for a department name.
Removed the hardcoded variable name from the filter. Now allows any variable to be filtered on to get the department name.
The variable change only affects the google analytics contrib content table collector and is only used by gov uk content.

Make filtersets compatible with Google Universal Analytics

---

performanceplatform/utils/http_with_backoff.py
tests/performanceplatform/utils/test_http_with_backoff.py

See https://developers.google.com/analytics/devguides/reporting/core/v3/coreErrors
We should retry when Google suggests it’s fine to retry, otherwise fail.
Also provide link so that it’s easier to troubleshoot configuration /
permissions problems.

Handle Google error codes appropriately

---

performanceplatform/collector/piwik/core.py
tests/fixtures/piwik_goal_completion_weekly.json
tests/performanceplatform/collector/piwik/test_core.py

Extend Piwik collector to support the Goals.get API method (and other methods where returned data points are not contained within a list). See https://www.pivotaltracker.com/story/show/95618296 for more information.

Add support for Goals.get API method

---

performanceplatform/collector/crontab.py
tests/performanceplatform/collector/test_crontab.py

When we migrate to gov.uk production, we will be running on 2 hosts
again, so we only need to split the jobs across 2 hosts.

Switch back to using 2 hosts for collectors

---

performanceplatform/collector/logging_setup.py
tests/performanceplatform/collector/test_logging_setup.py

Now we are on gov.uk infrastructure, there is a convention that
applications log to files production.json.log, and files that have the
extension .log. Although there is nothing in puppet to rotate these log
files, currently, we should rename them to be consistent with other apps
before adding to puppet.

Rename log files

---

requirements.txt

Mock is pulled in by dshelpers -
https://github.com/scraperwiki/data-services-helpers/blob/master/requirements.txt
This is pulling in the latest version, 1.3.0, which is not compatible
with the version of setuptools used on gov.uk infrastructure -
attempting to deploy gives the message
"mock requires setuptools>=17.1. Aborting installation"
As we dont require any later features in mock (yet...) it seems easier
to specify a version to install rather than changing which version of
setuptools is installed on the gov.uk infrastructure.

Specify a version for mock

---

performanceplatform/collector/main.py
tests/performanceplatform/collector/test_main.py

Argparse adds all command line arguments that have been set to mutually exclusive
to the return object. It then gives all of the keys that didn't appear on the
command line a value of None.
This was causing pp-collector to error when the query flag was passed and a
connection to stagecraft was not available. A connection to stagecraft should
only be attempted if the collector-slug flag is used.

Fix how mutually exclusive arguments are handled.

---

performanceplatform/utils/data_pusher.py
tests/performanceplatform/utils/test_data_pusher.py

None of the web traffic modules for Activity on GOV.UK that purport
to display information for the last seven days actually do so.
The module config only applies two filters on the data in the dataset
in backdrop: limiting the number of results returned to 10 and sorting
by the number of page views.
The dataset contains all data for the modules since records began.
Therefore if a page had more traffic in a week than any other for
whatever reason it will continue to be number one most viewed because
we aren't filtering by timestamp.
There are a couple of ways to filter by timestamp:
1. Pass in a start date and end date.
It's not possible to pass in dynamic dates to the module config, so
this has been ruled out.
2. Add filter parameters of duration and period to the module config.
This …

Add option to purge data set in GA collector

---

performanceplatform/collector/__init__.py

Bump to 0.2.0. This contains 193fea94f186f5fd9191bdaf0373627b14a846d5
which makes pip installing this package actually work

Bump version

---

performanceplatform/collector/__init__.py
setup.py

Trying to install the package on python3 gives the error "TypeError:
can't concat bytes to str". Removing the encode('ascii') works on both
python2 and python3 tested by installing from a local checkout using pyenv to
switch versions

Fix installation on python3

---

performanceplatform/collector/crontab.py
tests/performanceplatform/collector/test_crontab.py

The arguments from the crontab entry have been updated to pass a
collector slug to the pp-collector job rather than the location of
the collector configuration (query) file.
Dependent on: #126
Pivotal: https://www.pivotaltracker.com/story/show/98935742
Should be merged after the collector configs have been migrated to stagecraft.

Allow collector slug in crontab

---

performanceplatform/collector/__init__.py
performanceplatform/collector/ga/__init__.py
performanceplatform/collector/ga/core.py
performanceplatform/collector/ga/lib/helper.py
performanceplatform/collector/ga/realtime.py
performanceplatform/collector/ga/trending.py
requirements.txt
tests/performanceplatform/collector/ga/lib/test_helper.py
tests/performanceplatform/collector/ga/test_realtime.py

Extends the code responsible for creating GA clients (via the gapy library) to recognise when client secrets (dictionary) and OAuth 2.0 credentials (within a GA Storage Object) have been passed through from Stagecraft. This is in support of story https://www.pivotaltracker.com/story/show/100638120 which exposes an endpoint in Stagecraft for the execution of collectors.

Allow creds in ga config

---

performanceplatform/collector/__init__.py
performanceplatform/collector/logging_setup.py
performanceplatform/collector/main.py
tests/performanceplatform/collector/test_logging_setup.py
tests/performanceplatform/collector/test_main.py

Provide the facility for an application that imports performanceplatform-collector (e.g. Stagecraft) to output collector logs (JSON and non-JSON formats) to a filename and location of its choice, rather than to /log/production.*.
This has been achieved by extending the _run_collector method to support two new arguments: logfile_path and logfile_name.
Story: https://www.pivotaltracker.com/story/show/105753440

Log to stagecraft

---

performanceplatform/collector/__init__.py
performanceplatform/collector/logging_setup.py

Rotate log files (2 * 2GB files for JSON and non-JSON logs) to overcome file size issue in production.
Currently the log files are quickly reaching 40GB in size, which is causing a file write error and stalled processing of collector jobs (jobs left sitting in Rabbit MQ).
Story: https://www.pivotaltracker.com/story/show/107201116

Rotate logfiles

---

performanceplatform/collector/__init__.py
performanceplatform/collector/logging_setup.py
requirements.txt

Switch to ConcurrentLogHandler library in an attempt to overcome an issue with Celery not cleaning up log files on production due to its incompatibility with Python's RotatingFileHandler.

Concurrent log handler

---

performanceplatform/collector/__init__.py
performanceplatform/collector/logging_setup.py
performanceplatform/collector/main.py

When collectors are run in production via Celery, file descriptors for the JSON and non-JSON log handlers are not being removed when a job has completed. This is an attempt to resolve this by closing and removing all handlers on completion of a job.

Close down logging

---

README.rst
performanceplatform/collector/__init__.py
requirements.txt
requirements_for_tests.txt
tools/generate-ga-credentials.py

Google's oauth2client library now requires that command line flags are passed to its run_flow method via a mandatory 'flags' argument.
Use this flags argument (via a call to the gapy library's from_secrets_file method) to prevent oauth2client from opening a browser when running the generate-ga-credentials script.

Fix ga credentials script

---

.travis_scripts/push_release_tag.sh

Send `stdout` and `stderr` output to dev null so it does not appear in CI logs. If git push errors over https the output includes the GH auth token.

Silence output on push

---

.travis.yml
performanceplatform/collector/__init__.py
performanceplatform/collector/pingdom/core.py
requirements.txt
tests/performanceplatform/collector/pingdom/test_pingdom_api.py

We have moved to using the GaaP pingdom account, which is using
multi-user Pingdom.
In order to make requests to the Pingdom API for multi-user accounts we
must pass the header 'Account-Email', the value of which is
'gaap-billing@digital.cabinet-office.gov.uk'.
- Bump the version to 0.3.2
- Get the header from the config
- Pass the header to Pingdom
solo @tlwr

[159467985] Multi-user pingdom
